### ISSUE TITLE
Rebuild G'MIC for GIMP 2.99.6

### ISSUE THREAD

**Issue by Jehan** [flathub/org.gimp.GIMP.Plugin.GMic#11]
G'MIC-Qt just merged a patch to follow the GIMP API evolution: https://github.com/c-koi/gmic-qt/pull/112

So now it should build against libgimp 2.99.6. It would be nice to make a new build for the beta branch. 🙂

**Comment by hfiguiere** [comment]
ok. Will do.

**Comment by hfiguiere** [comment]
It doesn't seem to build with 2.99.6:

```
src/Host/Gimp/host_gimp.cpp: In function ‘GimpValueArray* gmic_qt_run(GimpProcedure*, GimpRunMode, GimpImage*, gint, GimpDrawable**, const GimpValueArray*, gpointer)’:
src/Host/Gimp/host_gimp.cpp:1157:5: error: ‘launchPlugin’ was not declared in this scope
 1157 |     launchPlugin(GmicQt::UserInterfaceMode::Full);
      |     ^~~~~~~~~~~~
src/Host/Gimp/host_gimp.cpp:1171:54: error: ‘pluginDialogWasAccepted’ was not declared in this scope
 1171 |   return gimp_procedure_new_return_values(procedure, pluginDialogWasAccepted() ? GIMP_PDB_SUCCESS : GIMP_PDB_CANCEL, NULL);
      |                                                      ^~~~~~~~~~~~~~~~~~~~~~~
[97/100] Building CXX object CMakeFiles/gmic_gimp_qt.dir/run/build/gmic/gmic/src/gmic.cpp.o
ninja: build stopped: subcommand failed.
```

**Comment by Jehan** [comment]
Indeed. If I try and build locally, I get the same error. But if I checkout the initially contributed patch, it works fine. It looks like G'MIC change their own API and the code broke during the merge (maybe were there some conflicts but they didn't properly testing rebuilding after having seemingly fixed these?).

It looks easy to fix. Let me have a look at contribute upstream.

**Comment by Jehan** [comment]
Ok. It works fine. I contributed the patch upstream: https://github.com/c-koi/gmic-qt/pull/113

In the meantime, if you want to patch in the Flatpak manifest directly (unless you prefer to wait for the patch to be merged):
https://patch-diff.githubusercontent.com/raw/c-koi/gmic-qt/pull/113.patch

**Comment by Jehan** [comment]
Well it's merged now! I believe a rebuild of the new HEAD will work. 🙂

**Comment by hfiguiere** [comment]
it's done with #12
